export const GET_MAIN_DATA_LOADING = "GET_MAIN_DATA_LOADING";
export const GET_MAIN_DATA_SUCCESS = "GET_MAIN_DATA_SUCCESS";
export const GET_MAIN_DATA_ERROR = "GET_MAIN_DATA_ERROR";

export const GET_POOL_POSITION_LOADING = "GET_POOL_POSITION_LOADING";
export const GET_POOL_POSITION_SUCCESS = "GET_POOL_POSITION_SUCCESS";
export const GET_POOL_POSITION_ERROR = "GET_POOL_POSITION_ERROR";
