export const GET_POOL_POSITION_LOADING = "GET_POOL_POSITION_LOADING";
export const GET_POOL_POSITION_SUCCESS = "GET_POOL_POSITION_SUCCESS";
export const GET_POOL_POSITION_ERROR = "GET_POOL_POSITION_ERROR";
