export const GET_MAIN_DATA_LOADING = "GET_MAIN_DATA_LOADING";
export const GET_MAIN_DATA_SUCCESS = "GET_MAIN_DATA_SUCCESS";
export const GET_MAIN_DATA_ERROR = "GET_MAIN_DATA_ERROR";

export const WEB3_INIT_SUCCESS = "WEB3_INIT_SUCCESS";
export const WEB3_INIT_ERROR = "WEB3_INIT_ERROR";
