export const GET_MAIN_DATA_LOADING = "GET_MAIN_DATA_LOADING";
export const GET_MAIN_DATA_SUCCESS = "GET_MAIN_DATA_SUCCESS";
export const GET_MAIN_DATA_ERROR = "GET_MAIN_DATA_ERROR";

// export const WEB3_INIT_SUCCESS = "WEB3_INIT_SUCCESS";
// export const WEB3_INIT_ERROR = "WEB3_INIT_ERROR";

export const ETH_BALANCE_SUCCESS = "ETH_BALANCE_SUCCESS";
export const ETH_BALANCE_ERROR = "ETH_BALANCE_ERROR";

export const RESET_ALL_LOCAL_REDUCER = "RESET_ALL_LOCAL_REDUCER";

export const CONNECT_USER = "CONNECT_USER";
export const DISCONNECT_USER = "DISCONNECT_USER";

export const SET_SLIPPAGE_ADD_LIQUIDITY = "SET_SLIPPAGE_ADD_LIQUIDITY";
export const SET_SLIPPAGE_REMOVE_LIQUIDITY = "SET_SLIPPAGE_REMOVE_LIQUIDITY";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";
