export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_USER_LOADING = "GET_USER_LOADING";
